Repository ros/catkin, pull requests merged in 2020-05, with the labels that each got.

#1090 fix -egg-base path to point to the build space
  cmake/catkin_python_setup.cmake
Labels: bug, consider-backport

#1088 Fix gtest_source_paths
  cmake/test/gtest.cmake
Labels: bug, consider-backport

#1091 fix GTest detection when cmake-extras is installed
  cmake/test/gtest.cmake
Labels: bug, consider-backport

#1093 suppress FPHSA name mismatch for empy
  cmake/empy.cmake
Labels: bug

#1086 [Windows] make more relocatable wrapper
  cmake/templates/python_win32_wrapper.cpp.in
Labels: enhancement

#1083 Stops catkin from trying to find C++ libraries if not needed
  cmake/test/gtest.cmake
  cmake/test/tests.cmake
  cmake/tools/rt.cmake
Labels: enhancement

#1095 error message python-empy -> python3-empy
  cmake/empy.cmake
Labels: bug
